# Kakoune user configuration
#

set current autowrap_column 80
hook global WinCreate .* %{
    addhl window wrap
    addhl global number_lines
    autowrap-enable
}

set current tabstop 4
set current indentwidth 0

# Use system clipboard

hook global NormalKey y|d|c %{ nop %sh{
    printf %s "$kak_reg_dquote" | xsel -ib
}}

map global user p '<a-!>xsel -ob<ret>'
map global user P '!xsel -ob<ret>'

# Hack to get backspace to delete indentwidth's word of spaces
map global insert <backspace> ⌫
hook global InsertChar ⌫ %{ try %{
    execute-keys <backspace>
    try %{
        execute-keys -draft hGh <a-k>\A +\z<ret> <lt>
    } catch %{
        execute-keys <backspace>
    }
}}

hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

hook global BufCreate .* %{editorconfig-load}

# The default filetype detection only includes *.tex
hook global BufCreate .*\.latex %{
    set buffer filetype latex
}

colorscheme onedark

