# Kakoune user configuration
#

set-option current autowrap_column 80

hook global WinCreate .* %{
    autowrap-enable
}

add-highlighter global/ wrap -word -indent -marker '↳ '
add-highlighter global/ show-matching
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ column '%opt{autowrap_column}' AutowrapColumn

set-option global tabstop 4

set-option global ui_options ncurses_assistant=none

set-option global grepcmd 'rg -Hn'

# Using smarttab plugin for this instead
# # Auto-expand tabs to spaces
# # TODO Put this in a plugin
# hook global InsertChar \t %{
#     execute-keys -draft ';h@'
# }

# hook global InsertDelete ' ' %{ try %{ execute-keys -draft %sh{
#     # Move indentwidth - 2 to the left
#     if test $kak_opt_indentwidth -le 1; then
#         exit
#     elif test $kak_opt_indentwidth -eq 2; then
#         # This has to be a separate case since 0h is the same as h, not nothing
#         echo ";h"
#     else
#         echo ";h$(( $kak_opt_indentwidth - 2 ))H"
#     fi
#     echo "<a-k>\A +\z<ret>d"
# }}}

# Setup IDE-ish mode
# TODO Not working
# rename-client main
# set-option global jumpclient main
# set-option global docsclient main
# set-option global toolsclient tools

# hook global BufCreate \*grep\* %{
#     evaluate-commands %sh{
#         if test -z %opt{toolsclient}; then
#             echo "set-option global toolsclient tools"
#             echo "tilix-new-vertical rename-client tools"
#             echo "tilix-focus tools"
#         fi
#     }
# }

# Load editorconfig
hook global BufCreate [^*].* %{ editorconfig-load }

source "%val{config}/mappings.kak"
source "%val{config}/plugins.kak"

