# Completions for xbps-rindex

# Autogenerated from man page /usr/share/man/man1/xbps-rindex.1
complete -c xbps-rindex -s d -l debug \
    --description 'Enables extra debugging shown to stderr.'
complete -c xbps-rindex -s f -l force \
    --description 'Forcefully register binary package into the local repository, overwriting exi…'
complete -c xbps-rindex -s h -l help \
    --description 'Show the help message.'
complete -c xbps-rindex -s V -l version \
    --description 'Show the version information.'

complete -x xbps-rindex -l signedby -r -f \
    --description "This is required to sign a repository."
complete -x xbps-rindex -l privkey -r \
    --description "Path to the private RSA key to sign the repository."

# TODO Allow this to take multiple files
complete -c xbps-rindex -s a -l add -r \
    -a "(__fish_complete_suffix .xbps)" \
    --description "Registers the binary package into the local repository."
complete -c xbps-rindex -s c -l clean -r \
    --description "Removes obsolete entries found in the local repository."
complete -c xbps-rindex -s r -l remove-obsoletes -r \
    --description "Removes obsolete packages from repository."
complete -c xbps-rindex -s s -l sign -r \
    --description "Initializes a signed repository with your specified RSA key."

