# Completions for xbps-checkvers

# Autogenerated from man page /usr/share/man/man1/xbps-checkvers.1
complete -c xbps-checkvers -s C -l config -r \
    --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-checkvers -s D -l distdir -r \
    --description 'Specifies a full path to the void-packages repository.'
complete -c xbps-checkvers -s d -l debug \
    --description 'Enables extra debugging shown to stderr.'
complete -c xbps-checkvers -s h -l help \
    --description 'Show the help message.'
complete -c xbps-checkvers -s i -l installed \
    --description 'Check for outdated installed packages rather than in repositories.'
complete -c xbps-checkvers -s R -l repository -r \
    --description 'Repository to be added to the top of the list.'
complete -c xbps-checkvers -s r -l rootdir -r \
    --description 'Specifies a full path for the target root directory.'
complete -c xbps-checkvers -s s -l show-missing \
    --description 'Shows missing binary packages comparing against the xbps-checkvers void-packa…'
complete -c xbps-checkvers -s V -l version \
    --description 'Show the version information.'

