# Completions for xbps-create

# Autogenerated from man page /usr/share/man/man1/xbps-create.1
complete -c xbps-create -s A -l architecture -r -f \
    --description 'The target architecture for this package (required).'
complete -c xbps-create -s B -l built-with -r -f \
    --description 'The package builder string, free form.'
complete -c xbps-create -s C -l conflicts -r -f \
    -a "(xbps-query -Rs '' | sed -e 's/\[.\] \([^ \t\n]\+\)-.*/\1/')" \
    --description 'A list of package patterns that this package should conflict with, separated …'
complete -c xbps-create -s D -l dependencies -r -f \
    -a "(xbps-query -Rs '' | sed -e 's/\[.\] \([^ \t\n]\+\)-.*/\1/')" \
    --description 'A list of package patterns this package depends on, separated by whitespaces.'
complete -c xbps-create -s F -l config-files -r -f \
    -a "(xbps-query -Rs '' | sed -e 's/\[.\] \([^ \t\n]\+\)-.*/\1/')" \
    --description 'A list of configuration files this package provides, separated by whitespace.'
complete -c xbps-create -s G -l source-revisions -r -f \
    --description 'This sets a string with the git revisions of the sourcepkg that was used to b…'
complete -c xbps-create -s H -l homepage -r -f \
    --description 'The package homepage string.'
complete -c xbps-create -s h -l help \
    --description 'Show the help message.'
complete -c xbps-create -s l -l license \
    --description 'The package license.'
complete -c xbps-create -s M -l mutable-files -r \
    --description 'A list of mutable files this package provides, separated by whitespaces.'
complete -c xbps-create -s m -l maintainer -r -f \
    --description 'The package maintainer name and/or email contact.'
complete -c xbps-create -s n -l pkgver -r -f \
    --description 'The package name/version tuple, e. g: \'foo-1. 0_1\'.'
complete -c xbps-create -s P -l provides -r -f \
    -a "(xbps-query -Rs '' | sed -e 's/\[.\] \([^ \t\n]\+\)-.*/\1/')" \
    --description 'A list of virtual packages this package provides, separated by whitespaces.'
complete -c xbps-create -s p -l preserve \
    --description 'If set the package files will be preserved after being updated.'
complete -c xbps-create -s q -l quiet \
    --description 'Enable quiet operation.'
complete -c xbps-create -s R -l replaces -r -f \
    -a "(xbps-query -Rs '' | sed -e 's/\[.\] \([^ \t\n]\+\)-.*/\1/')" \
    --description 'A list of package patterns this package replaces, separated by whitespaces.'
complete -c xbps-create -s r -l reverse -r -f \
    --description 'A list of versions this package reverts, separated by whitespaces.'
complete -c xbps-create -s S -l long-desc -r -f \
    --description 'A long description for this package.'
complete -c xbps-create -s s -l desc -r -f \
    --description 'A short description for this package, one line with less than 80 characters.'
complete -c xbps-create -s t -l tags -r -f \
    --description 'A list of tags (categories) this package should be part of, separated by whit…'
complete -c xbps-create -s V -l version \
    --description 'Show the version information.'

complete -c xbps-create -l build-options -r -f \
    --description 'A string containing the build options used in package.'
complete -c xbps-create -l compression -r -f -a "gzip bzip2 xz" \
    --description 'Set the binary package compression format.  If unset, defaults to xz.'
complete -c xbps-create -l shlib-provides -r \
    --description 'A list of provided shared libraries, separated by whitespaces.'
complete -c xbps-create -l shlib-requires -r \
    --description 'A list of required shared libraries, separated by whitespaces.'
complete -c xbps-create -l alternatives -r \
    --description 'A list of alternatives provided by this package, separated by whitespaces.'
complete -c xbps-create -s c -l changelog -r -f \
    --description "The package changelog string."

