# Completions for xbps-dgraph

function __has_option
    commandline | grep -- '[ \t\n]-'"$1"
end

complete -c xbps-dgraph -n "__has_option R" \
    -a "(xbps-query -Rs '' | sed -e 's/\[.\] \([ \t\n]\+\)-.*/\1/')"
complete -c xbps-dgraph -n "not __has_option R" \
    -a "(xbps-query -l | sed -e 's/.. \([ \t\n]\+\)-.*/\1/')"

# Autogenerated from man page /usr/share/man/man1/xbps-dgraph.1
complete -c xbps-dgraph -s C -l config -r \
    --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-dgraph -s c -l graph-config -r \
    --description 'Specifies a path to the graph configuration file, to modify the settings of t…'
complete -c xbps-dgraph -s d -l debug \
    --description 'Enables extra debugging shown to stderr.'
complete -c xbps-dgraph -s h -l help \
    --description 'Show the help message.'
complete -c xbps-dgraph -s M -l memory-sync \
    --description 'For remote repositories, the data is fetched and stored in memory for the cur…'
complete -c xbps-dgraph -s R -l repository \
    --description 'Enable repository mode.'
complete -c xbps-dgraph -s r -l rootdir -r \
    --description 'Specifies a full path for the target root directory.'
complete -c xbps-dgraph -s V -l version \
    --description 'Show the version information.'

complete -c xbps-dgraph -s g -l gen-config \
    --description 'Generates a graph configuration file in the current working directory.'
complete -c xbps-dgraph -s f -l fulldeptree \
    --description 'Generates a full dependency graph of the target package.'
complete -c xbps-dgraph -s m -l metadata \
    --description 'Generates a metadata graph of the target package.'

