# Completionsn for xbps-remove

complete -c xbps-remove \
    -a "(xbps-query -l | sed -e 's/^.. \([^ \t\n]\+\)-.*/\1/')"

# Autogenerated from man page /usr/share/man/man1/xbps-remove.1
complete -c xbps-remove -s C -l config -r \
    -a "(__fish_complete_directories '' '')" \
    --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-remove -s c -l cachedir -r \
    -a "(__fish_complete_directories '' '')" \
    --description 'Specifies a path to the cache directory, where binary packages are stored.'
complete -c xbps-remove -s d -l debug \
    --description 'Enables extra debugging shown to stderr.'
complete -c xbps-remove -s F -l force-revdeps \
    --description 'Forcefully remove package even if there are reverse dependencies and/or broke…'
complete -c xbps-remove -s f -l force \
    --description 'Forcefully remove package files even if they have been modified.'
complete -c xbps-remove -s h -l help \
    --description 'Show the help message.'
complete -c xbps-remove -s n -l dry-run \
    --description 'Dry-run mode.  Show what actions would be done but don\'t do anything.'
complete -c xbps-remove -s O -l clean-cache \
    --description 'Cleans cache directory removing obsolete binary packages.'
complete -c xbps-remove -s o -l remove-orphans \
    --description 'Removes installed package orphans that were installed automatically (as depen…'
complete -c xbps-remove -s R -l recursive \
    --description 'Recursively remove packages that were installed by PKGNAME and aren\'t require…'
complete -c xbps-remove -s r -l rootdir -r \
    -a "(__fish_complete_directories '' '')" \
    --description 'Specifies a full path for the target root directory.'
complete -c xbps-remove -s v -l verbose \
    --description 'Enables verbose messages.'
complete -c xbps-remove -s y -l yes \
    --description 'Assume yes to all questions and avoid interactive questions.'
complete -c xbps-remove -s V -l version \
    --description 'Show the version information.  El FILES -tag -width /var/db/xbps/.'

